### ISSUE TITLE
Add Decay prediction / functionality

### ISSUE THREAD

**Issue by soFFe** [soFFe/ClassicEraHonorCalculator#4]

**Comment by Ne0-1** [comment]
Any1 knows how decay works? Is it 20% of your CP with a cap that you can't drank still? Or will you only decay if you don't qualify for your current rank?

**Comment by soFFe** [comment]
1. Decay happens only if you don't at least qualify for your current Rank.
2. You can only decay up to 2500 CP.
3. We don't know the formula to get the decayed amount of CP yet.

**Comment by soFFe** [comment]
`NextWeekCp = CurrentCp - min(2500, CurrentCp - CurrentRankCpRequirement)`
